./sta -id 1 -name " $(date +%H:%M) "
./sta -id 2 -name " $(date +'%b %d')                                    "
./sta -id 3 -name " $(cat /sys/class/power_supply/BAT1/status) "
./sta -id 4 -name "   $(cat /sys/class/power_supply/BAT1/capacity)% │"
./sta -id 5 -name "   $(light -G | awk '{print int($1)}')% │"
./sta -id 6 -name "   $(pamixer --get-volume) │"
./sta -id 7 -name "  $(top -bn1 | grep "Cpu(s)" | awk '{print int($2 + $4)}')% /"
./sta -id 8 -name "  $(cat /sys/class/thermal/thermal_zone3/temp | awk '{print int($1/1000)}')󰔄 │"
./sta -id 9 -name "   $(free -h | awk '/^Mem:/ {print $3}') │"
./sta -id 10 -name "  $(df -h /home/ | awk 'NR==2 {print $5}') │"
./sta -id 11 -name "   $(cat /proc/net/wireless | awk 'NR>2 {print $1}' | head -n1)  "
